redash:
  image: redash
  ports:
    - "5000:5000"
  links:
    - redis
    - postgres
  env_file: .env
redis:
  image: redis:2.8
postgres:
  image: postgres:9.3
  volumes:
   - /opt/postgres-data:/var/lib/postgresql/data
redash-nginx:
  image: redash-nginx:1.0
  ports:
    - "80:80"
  volumes:
    - "../redash-nginx/nginx.conf:/etc/nginx/nginx.conf"
  links:
    - redash
